import type { AssetExtractionEpisodeInput } from './types'

function serializeEpisodes(episodes: AssetExtractionEpisodeInput[]): string {
  return episodes
    .map((episode) => [
      `第${episode.episodeNumber}集：${episode.title || `第${episode.episodeNumber}集`}`,
      episode.sourceText,
    ].join('\n'))
    .join('\n\n')
}

export function buildAssetExtractionPrompt(input: {
  episodes: AssetExtractionEpisodeInput[]
}): string {
  return [
    '你是精品短剧资产事实抽取助手。当前步骤只负责从输入剧集中抽取结构化资产 JSON：角色定位、时期划分、身份阶层、剧情状态、明确视觉线索、道具和环境事实。后续会有“视觉设定 refine”步骤根据时期身份生成最终 subject/face/clothing/accessories，再由固定模板生成角色定稿图、环境定稿图、道具定稿图提示词。请只根据输入剧集文本抽取可复用资产，输出严格紧凑 JSON，不要缩进，不要 Markdown，不要解释。',
    '',
    '重要规则：',
    '1. 不要改分集，不要新增集数，不要重写剧情。',
    '2. 当前输入通常是全剧中的 3 集局部批次；只抽取本批次文本里有依据的资产，不要假装已经看完全剧。',
    '3. 角色必须区分主角、核心配角、配角。',
    '4. 角色资产用于后续生图：主角、核心配角、小角色都可以抽取；不要抽“追兵、侍卫若干、丫鬟们、下人甲乙、蒙面人”等无稳定身份的群体角色。',
    '5. 每个角色必须有“角色背景”和显式 mainAppearance（主形象/身份基准）。角色背景用于理解剧情；mainAppearance.facts 用于描述稳定身份、阶层、处境、明确视觉线索。',
    '6. mainAppearance 必须包含 name、episodeRange、facts、profile、reason、evidence；name 必须是“身份/社会位置 + 时期”，例如陆府姨太时期、被贬副官时期。',
    '7. facts 是本阶段的重点：identity 写该时期身份，socialStatus 写阶层/处境，plotState 写剧情状态，explicitVisualCues 只写原文明确出现或强相关的视觉线索。',
    '8. profile 只是初步视觉草案，不是最终定稿图档案；每个字段控制在 40 个中文以内，只写身份/线索摘要，不要展开完整服装材质、版型、脸部比例。后续 refine 会补全完整 subject、face、clothing、accessories。',
    '9. 主形象 profile 是角色的稳定身份基准/默认设定，不是每个 episode 的即时状态。不要选择雨夜逃亡、重伤、临盆、病危、濒死等一次性极端状态作为默认主形象；这些应放入 variants。',
    '10. 角色 variants 是“状态变体/身份阶段叠加”，必须绑定 episodeRange，只描述相对主形象的变化，例如受伤、淋雨、饥饿、护胎、遇袭、逃亡、身份升级、老年化等。',
    '11. 环境和道具本阶段也只输出短草案 profile；完整生图档案后续再补。每个 profile 字段 35 字以内。物品没有 variants 字段，也不做“物品变体”结构。',
    '12. 每个资产必须带 evidence，quote 必须摘自输入文本；每个资产最多 2 条 evidence，每条 quote 控制在 50 字以内。',
    '13. 输出必须极度精简：单批总 JSON 尽量控制在 8000 中文字符以内。宁可少写小角色/次要道具/重复环境，也不要长篇展开。',
    '',
    '与目标资产卡片对齐：',
    '- 最终角色卡片会展示“角色名、重要性、覆盖集数、角色背景、角色提示词、若干状态变体/身份阶段”。覆盖集数由 relatedEpisodes 推导，不要额外输出 EP 文本字段。',
    '- 不要输出完整的角色设定图构图模板，不要输出【整体美学】、【画面规格】、左40%/右60%等版面文字；这些由下游固定模板生成。',
    '- mainAppearance 是默认主形象/身份基准，必须有自己的 name、episodeRange 和 facts；profile 是兼容字段，必须复制 mainAppearance.profile，但它只是初稿，最终会被 refine 覆盖。',
    '- variants 是“相对 mainAppearance”的叠加变化素材，不要把主形象身份基准也重复放进 variants。',
    '- 变体命名规则：同一主身份下的受辱、断食、护胎、遇袭、晕倒等写“xx状态”；真正身份/人生阶段变化才写“xx时期”，例如：柴房被卖时期、逃亡孤女时期、老年时期。不要使用“第1-3集视觉阶段”“第6-10集视觉阶段”这类泛化名称。',
    '- 变体 profileOverride 只写短线索，每字段 40 字以内；完整“相对主形象”的服装/发型/面色/配饰文案由 refine 阶段生成。',
    '',
    '角色抽取策略：',
    '- 剧本文本中的“人物：”行是角色覆盖集数的重要依据。只要一个已抽取角色出现在本批某集“人物：”行里，就必须把该集加入 relatedEpisodes，并给出对应 evidence。',
    '- 有明确姓名/称谓且需要单独生图的小角色也要抽成 supporting，例如春桃、王媒婆、西医、陈阿婆这类有独立行动或台词的人物。',
    '- 主角和核心配角优先抽完整，不要漏集数；普通 supporting 角色可以只有主形象和 relatedEpisodes，不需要变体。',
    '- 别名要进入 aliases，例如“我（苏晚卿）”中“我”和“苏晚卿”都要能指向同一个角色，“陆副官/副官/承煜”都应归到陆承煜。',
    '- 单批最多输出 8 个角色；优先主角、核心配角、有名字且可生图的小角色。群像、无姓名称谓、一次性打手不要输出。',
    '',
    '角色时期事实标准：',
    '- mainAppearance.name 必须优先用稳定身份/社会位置命名，例如“陆府姨太时期”“被贬副官时期”；若本批次只看到单集常态，也要命名为语义身份基准，不要写“主形象时期”。',
    '- identity 必须写角色在该时期的身份，例如“陆府低位姨太”“逃亡孤女”“督军府副官”“陆府丫鬟”。',
    '- socialStatus 必须写阶层和待遇，例如“已进入陆府内宅但被冷落打压”“乡野底层无依无靠”“军政体系副官，有调度侍卫能力”。',
    '- plotState 必须写该时期剧情状态，例如“初入陆府受辱、断食并开始反击”。',
    '- explicitVisualCues 只写文本明确或强相关视觉证据，例如“脸色惨白”“被扇耳光红痕”“浑身湿透”“贴身藏令牌”。',
    '- explicitVisualCues 最多 5 条，每条 20 字以内。',
    '',
    '初步 profile 草案标准（瘦身输出）：',
    '- subject：只写性别、年龄段、身份、体型/姿态摘要，40 字以内。',
    '- face：只写原文明确面色/伤痕/发型线索；没有就写“待 refine 补全面部”。',
    '- clothing：只写原文明确衣着线索或“按身份 refine 服装”；不要生成完整服装方案。',
    '- accessories：只写令牌、银簪、玉镯、武器等明确道具线索。',
    '- background 可以写人物经历、动机、关系、别名；profile 不要写抽象剧情评价，要写可画出来的视觉信息。',
    '- background 控制在 80 字以内；reason 控制在 40 字以内。',
    '',
    'GPT Image 2 提示词要求：',
    '- 第一阶段 profile 不直接生图，第二阶段 refine 后的 profile 才会进入【角色档案】模板。',
    '- 使用具体名词和视觉短语，不要写“很有故事感、气质复杂、命运感强”这种不可直接生图的词。',
    '- 不要加入镜头语言、构图、景别、光效，除非它是资产本身的稳定视觉属性。镜头语言留给后续分镜。',
    '- 不要把剧情动作写进默认 clothing/face；动作、伤病、湿透、饥饿、临盆、老年等状态放到 variants.profileOverride。',
    '',
    '变体规则：',
    '- 只有主角 lead 和核心配角 core_supporting 可以有 variants。主角通常 2-4 个变体，核心配角通常 0-2 个变体，普通配角 supporting 必须输出空 variants 数组。',
    '- 变体命名优先级：身份阶段变化 > 同身份重大状态 > 单集剧情事件。同身份下能叫“陆府断食受辱状态”就不要叫“陆府姨太时期”；护胎/遇袭/晕倒/受辱都是状态，不是新的主身份。',
    '- 每个变体必须覆盖 episodeRange，episodeRange 只使用输入剧集范围内的集数。',
    '- profileOverride 只写相对主形象变化的短线索字段。没有变化的字段可以省略或留空字符串。',
    '- name 必须以“状态”或“时期”结尾，且前缀必须是语义阶段，不要直接用集数命名。',
    '- 示例变体：柴房被卖时期、逃亡孤女时期、陆府断食受辱状态、陆府护胎状态、偏院遇袭护胎状态、督军夫人时期、老年安享时期。',
    '- reason 说明为什么后续生图需要这个变体，例如身份变化、服装变化、年龄变化、伤病状态或核心道具变化。',
    '- 单个 lead 在本批最多 2 个 variants；core_supporting 最多 1 个 variants；supporting 必须 0 个 variants。',
    '',
    '环境/道具短草案标准：',
    '- 单批最多输出 6 个环境、8 个道具；合并同类地点和同类物件，例如“陆府小院/陆府内宅”不要重复拆很多。',
    '- environment.profile.subject/layout/atmosphere/visualDetails 每项 35 字以内，只写稳定空间线索。',
    '- prop.profile.subject/material/shape/visualDetails 每项 35 字以内，只写物件事实线索。',
    '- 物品不输出 variants，也不要把“断裂银簪、变形令牌、踩压令牌、小院油灯”等状态拆成物品变体。它们仍作为同一个物品资产合并，状态差异写进 background/profile.visualDetails/evidence。',
    '',
    '不要输出这些低质量档案：',
    '- “年轻女子，长得漂亮，气质倔强。”',
    '- “穿古装，表情复杂。”',
    '- “一个很有压迫感的男人。”',
    '- “豪门宅院，氛围高级。”',
    '- “第1-3集视觉阶段。”',
    '',
    '输出 JSON schema（照此字段输出紧凑 JSON，不要 pretty print）：',
    JSON.stringify({
      version: 'asset-extraction-v1',
      worldBackground: '全局故事背景。只描述故事时代、地点范围、权力结构、整体氛围等，不写分集摘要。',
      characters: [
        {
          id: 'character-su-wanqing',
          name: '苏晚卿',
          aliases: ['我', '苏姨太'],
          importance: 'lead',
          background: '被迫进入陆府的底层孤女，受辱后冷静反击。',
          mainAppearance: {
            id: 'character-su-wanqing-main-lufu-concubine',
            name: '陆府姨太时期',
            episodeRange: { start: 1, end: 3 },
            facts: {
              identity: '陆府低位姨太',
              socialStatus: '已进入陆府内宅体系，但地位低，被正得势姨太压制，生活寒酸受限。',
              plotState: '初入陆府，受辱、断食，但开始冷静设局反击。',
              explicitVisualCues: ['脸颊红痕', '贴身藏陆字令牌'],
            },
            profile: {
              subject: '女性约18岁，陆府低位姨太，纤细隐忍。',
              face: '被扇耳光红痕，脸色苍白。',
              clothing: '按陆府低位姨太身份 refine 服装。',
              accessories: '贴身藏陆字令牌，银簪。',
            },
            reason: '本批稳定身份基准。',
            evidence: [{ episodeNumber: 1, quote: '原文证据' }],
          },
          profile: {
            subject: '女性约18岁，陆府低位姨太，纤细隐忍。',
            face: '被扇耳光红痕，脸色苍白。',
            clothing: '按陆府低位姨太身份 refine 服装。',
            accessories: '贴身藏陆字令牌，银簪。',
          },
          variants: [
            {
              id: 'character-su-wanqing-variant-escape',
              name: '柴房被卖时期',
              episodeRange: { start: 1, end: 3 },
              facts: {
                identity: '逃亡孤女',
                socialStatus: '乡野底层，无依无靠，被卖后逃亡。',
                plotState: '被生母卖给恶霸后逃出柴房，在雨夜土地庙避难。',
                explicitVisualCues: ['湿透沾泥', '面色惨白', '手攥银簪'],
              },
              backgroundDelta: '被卖后雨夜逃亡。',
              profileOverride: {
                subject: '药效未退，踉跄狼狈，手臂淤青。',
                face: '面色惨白，唇色发紫，冷汗雨水。',
                clothing: '粗布衣裤湿透沾泥。',
                accessories: '手攥银簪，掌心划伤。',
              },
              reason: '逃亡装束和伤病状态差异大。',
              evidence: [{ episodeNumber: 1, quote: '原文证据' }],
            },
          ],
          relatedEpisodes: [1, 2, 3],
          evidence: [{ episodeNumber: 1, quote: '原文证据' }],
        },
      ],
      environments: [
        {
          id: 'environment-land-temple',
          name: '城郊土地庙',
          background: '雨夜逃亡避难和围堵场景。',
          profile: {
            subject: '城郊破旧土地庙。',
            layout: '单进小庙，供台和墙角可藏身。',
            atmosphere: '夜雨阴冷、荒僻压抑。',
            visualDetails: '破木门、泥水脚印、旧供台。',
          },
          relatedEpisodes: [1, 2],
          evidence: [{ episodeNumber: 1, quote: '原文证据' }],
        },
      ],
      props: [
        {
          id: 'prop-silver-hairpin',
          name: '银簪',
          background: '苏晚卿贴身信物和临时武器。',
          profile: {
            subject: '女子贴身细长银簪。',
            material: '旧银，冷白金属光。',
            shape: '细长簪身，簪尖锋利。',
            visualDetails: '雨水冷光，可手攥。',
          },
          owner: '苏晚卿',
          relatedEpisodes: [1],
          evidence: [{ episodeNumber: 1, quote: '原文证据' }],
        },
      ],
      warnings: [],
    }),
    '',
    '输入剧集文本：',
    serializeEpisodes(input.episodes).slice(0, 80_000),
  ].join('\n')
}
